# Generated by Django 2.2.12 on 2020-05-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_auto_20200524_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='Department_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
