# Generated by Django 2.2.12 on 2020-05-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('worker_email', models.EmailField(max_length=254)),
                ('worker_phno', models.IntegerField()),
                ('worker_typer', models.CharField(max_length=50)),
            ],
        ),
    ]
