# Generated by Django 2.2.12 on 2020-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_workertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertype',
            name='type',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
