# Generated by Django 2.2.12 on 2020-05-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('problem_type', models.TextField()),
                ('department', models.CharField(max_length=50)),
                ('roomno', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('complaint_status', models.CharField(default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.IntegerField()),
            ],
        ),
    ]
